### PR TITLE
removed all white backgrounds of images

### LINKED ISSUE #2: [FEAT] Make background for certain images transparent.
I require the background for the white background images to be made transparent, if possible.

image

### PR DESCRIPTION
**Pull request by danielafriheart**
fixes #2 

Backgrounds removed from images.

### CODE REVIEW

**Review by KendallDoesCoding — CHANGES_REQUESTED** [review]
Thanks a ton! Looks amazing, but can you please add the background back of: 
image because it looks very weird without the background.

**Comment by KendallDoesCoding** [comment]
> Thanks a ton! Looks amazing, but can you please add the background back of: image because it looks very weird without the background.

Reminder!

**Comment by danielafriheart** [comment]
> > Thanks a ton! Looks amazing, but can you please add the background back of: image because it looks very weird without the background.
> 
> Reminder!

Done, check it out

**Comment by KendallDoesCoding** [comment]
Perfect! Thanks for your contribution.

**Review by KendallDoesCoding — APPROVED** [review]

**Pull request merged**
